# Generated by Django 3.1.5 on 2021-02-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210215_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('Grocery', 'Grocery'), ('Appliances', 'Appliances'), ('Beauty', 'Beauty'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('HomeFurniture', 'HomeFurniture'), ('Mobile', 'Mobile'), ('Toy', 'Toy')], default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
