# Generated by Django 3.1.5 on 2021-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210215_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Appliances', 'Appliances'), ('Beauty', 'Beauty'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('HomeFurniture', 'HomeFurniture'), ('Mobile', 'Mobile'), ('Toy', 'Toy')], default=1, max_length=200),
        ),
    ]
