# Generated by Django 3.1.5 on 2021-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210221_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=' ', max_length=225),
        ),
    ]
