# Generated by Django 3.1.5 on 2021-02-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
